require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec


AllCops:
  TargetRubyVersion: 2.7
  TargetRailsVersion: 5.2
  Exclude:
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'vendor/bundle/**/*'
    - 'bin/**/*'
    - 'app/helpers/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/rails_helper.rb'


Layout/LineLength:
  Max: 160

Metrics/MethodLength:
  Max: 23

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

RSpec/ExampleLength:
  Max: 7
